#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bcache-tools
Version  : 494f8d187c74f557dfebbb5dc3591453436b507b
Release  : 3
URL      : https://github.com/koverstreet/bcache-tools/archive/494f8d187c74f557dfebbb5dc3591453436b507b.tar.gz
Source0  : https://github.com/koverstreet/bcache-tools/archive/494f8d187c74f557dfebbb5dc3591453436b507b.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: bcache-tools-bin = %{version}-%{release}
Requires: bcache-tools-config = %{version}-%{release}
Requires: bcache-tools-data = %{version}-%{release}
Requires: bcache-tools-license = %{version}-%{release}
Requires: bcache-tools-man = %{version}-%{release}
BuildRequires : pkgconfig(blkid)
BuildRequires : pkgconfig(uuid)
BuildRequires : util-linux-dev
Patch1: 0001-Don-t-inline-crc64-for-gcc-5-compatibility.patch
Patch2: 0002-Fix-installation-paths.patch

%description
These are the userspace tools required for bcache.
Bcache is a patch for the Linux kernel to use SSDs to cache other block
devices. For more information, see http://bcache.evilpiepirate.org.
Documentation for the run time interface is included in the kernel tree, in
Documentation/bcache.txt.

%package bin
Summary: bin components for the bcache-tools package.
Group: Binaries
Requires: bcache-tools-data = %{version}-%{release}
Requires: bcache-tools-config = %{version}-%{release}
Requires: bcache-tools-license = %{version}-%{release}

%description bin
bin components for the bcache-tools package.


%package config
Summary: config components for the bcache-tools package.
Group: Default

%description config
config components for the bcache-tools package.


%package data
Summary: data components for the bcache-tools package.
Group: Data

%description data
data components for the bcache-tools package.


%package license
Summary: license components for the bcache-tools package.
Group: Default

%description license
license components for the bcache-tools package.


%package man
Summary: man components for the bcache-tools package.
Group: Default

%description man
man components for the bcache-tools package.


%prep
%setup -q -n bcache-tools-494f8d187c74f557dfebbb5dc3591453436b507b
cd %{_builddir}/bcache-tools-494f8d187c74f557dfebbb5dc3591453436b507b
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586369885
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1586369885
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bcache-tools
cp %{_builddir}/bcache-tools-494f8d187c74f557dfebbb5dc3591453436b507b/COPYING %{buildroot}/usr/share/package-licenses/bcache-tools/b47456e2c1f38c40346ff00db976a2badf36b5e3
%make_install UDEVLIBDIR=/usr/lib/udev DRACUTLIBDIR=/usr/lib/dracut

%files
%defattr(-,root,root,-)
/usr/lib/dracut/modules.d/90bcache/module-setup.sh
/usr/lib/initcpio/install/bcache
/usr/lib/udev/bcache-register
/usr/lib/udev/probe-bcache

%files bin
%defattr(-,root,root,-)
/usr/bin/bcache-super-show
/usr/bin/make-bcache

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/69-bcache.rules

%files data
%defattr(-,root,root,-)
/usr/share/initramfs-tools/hooks/bcache

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bcache-tools/b47456e2c1f38c40346ff00db976a2badf36b5e3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/bcache-super-show.8
/usr/share/man/man8/make-bcache.8
/usr/share/man/man8/probe-bcache.8
