#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : bcache-tools
Version  : 1.1
Release  : 4
URL      : file:///aot/build/clearlinux/packages/bcache-tools/bcache-tools-v1.1.tar.gz
Source0  : file:///aot/build/clearlinux/packages/bcache-tools/bcache-tools-v1.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: bcache-tools-bin = %{version}-%{release}
Requires: bcache-tools-config = %{version}-%{release}
Requires: bcache-tools-data = %{version}-%{release}
Requires: bcache-tools-man = %{version}-%{release}
BuildRequires : openssl-dev
BuildRequires : openssl-staticdev
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(blkid)
BuildRequires : pkgconfig(uuid)
BuildRequires : util-linux-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-Makefile.patch

%description
These are the userspace tools required for bcache.
Bcache is a patch for the Linux kernel to use SSDs to cache other block
devices. For more information, see http://bcache.evilpiepirate.org.
Documentation for the run time interface is included in the kernel tree, in
Documentation/bcache.txt.

%package bin
Summary: bin components for the bcache-tools package.
Group: Binaries
Requires: bcache-tools-data = %{version}-%{release}
Requires: bcache-tools-config = %{version}-%{release}

%description bin
bin components for the bcache-tools package.


%package config
Summary: config components for the bcache-tools package.
Group: Default

%description config
config components for the bcache-tools package.


%package data
Summary: data components for the bcache-tools package.
Group: Data

%description data
data components for the bcache-tools package.


%package dev
Summary: dev components for the bcache-tools package.
Group: Development
Requires: bcache-tools-bin = %{version}-%{release}
Requires: bcache-tools-data = %{version}-%{release}
Provides: bcache-tools-devel = %{version}-%{release}
Requires: bcache-tools = %{version}-%{release}

%description dev
dev components for the bcache-tools package.


%package man
Summary: man components for the bcache-tools package.
Group: Default

%description man
man components for the bcache-tools package.


%prep
%setup -q -n bcache-tools
cd %{_builddir}/bcache-tools
%patch1 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1627195931
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-g -O2"
#  -march=native -mtune=native
export CXXFLAGS="-g -O2"
#
export FCFLAGS="-g -O2"
export FFLAGS="-g -O2"
export CFFLAGS="-g -O2"
#
export LDFLAGS="-g -O2"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export LD_LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export LIBRARY_PATH="/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/haswell:/usr/lib64/dri:/usr/lib64/chromium:/usr/lib64:/usr/lib64/pulseaudio:/usr/lib64/alsa-lib:/usr/lib64/gstreamer-1.0:/usr/lib64/pipewire-0.3:/usr/lib64/spa-0.2:/usr/lib:/aot/intel/oneapi/compiler/latest/linux/compiler/lib/intel64_lin:/aot/intel/oneapi/compiler/latest/linux/lib:/aot/intel/oneapi/mkl/latest/lib/intel64:/aot/intel/oneapi/tbb/latest/lib/intel64/gcc4.8:/usr/share:/usr/lib64/wine:/usr/nvidia/lib32:/usr/nvidia/lib32/vdpau:/usr/lib32:/usr/lib32/wine"
#
export PATH="$PATH:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="/usr/local/cuda/include"
#
## altflags1 end
make  %{?_smp_mflags}    V=1 VERBOSE=1


%install
export SOURCE_DATE_EPOCH=1627195931
rm -rf %{buildroot}
%make_install UDEVLIBDIR=/usr/lib/udev DRACUTLIBDIR=/usr/lib/dracut

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bcache
/usr/bin/bcache-status
/usr/bin/bcache-super-show
/usr/bin/make-bcache

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/69-bcache.rules

%files data
%defattr(-,root,root,-)
/usr/share/initramfs-tools/hooks/bcache

%files dev
%defattr(-,root,root,-)
/usr/lib/dracut/modules.d/90bcache/module-setup.sh
/usr/lib/initcpio/install/bcache
/usr/lib/udev/bcache-export-cached
/usr/lib/udev/bcache-register
/usr/lib/udev/probe-bcache

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/bcache-status.8
/usr/share/man/man8/bcache-super-show.8
/usr/share/man/man8/make-bcache.8
/usr/share/man/man8/probe-bcache.8
